---
resources:
- name: om
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf/om

jobs:
- name: whats-inside-om
  plan:
  - get: om
  - task: ls-om
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/bosh-cli}
      inputs:
      - name: om
      run:
        path: sh
        args:
        - -c
        - |
          ls ./om
