jobs:
- name: say-hello
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/bosh-cli}
      run:
        path: sh
        args:
        - -c
        - |
          echo "hello"
