---
resources:
- name: om
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf/om

jobs:
- name: whats-inside-om
  plan:
  - get: om
  - task: touch-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/bosh-cli}
      inputs:
      - name: om
      outputs:
      - name: updated-om
      run:
        path: sh
        args:
        - -c
        - |
          touch om/new-file
          cp -r om/* updated-om

  - task: ls-updated-om
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/bosh-cli}
      inputs:
      - name: updated-om
      run:
        path: sh
        args:
        - -c
        - |
          ls updated-om
