---
resources:
- name: ci-repo
  type: git
  source:
    branch: master
    uri: git@github.com:joshzarrabi/concourse-pres
    private_key: ((git_key))

jobs:
- name: update-our-repo
  plan:
  - get: ci-repo
  - task: touch-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: concourse/bosh-cli}
      inputs:
      - name: ci-repo
      outputs:
      - name: updated-ci-repo
      run:
        path: sh
        args:
        - -c
        - |
          cd ci-repo > /dev/null
            touch new-file
            git config --global user.email "josh-bot@pivotal.io"
            git config --global user.name "Josh Bot"
            git checkout master
            git add .
            git commit -m "add file"
          cd -
          cp -r ci-repo/. updated-ci-repo
  - put: ci-repo
    params:
      repository: updated-ci-repo

