resources:
- name: om
  type: git
  source:
    branch: master
    uri: https://github.com/pivotal-cf/om

- name: ci-repo
  type: git
  source:
    branch: master
    uri: https://github.com/joshzarrabi/concourse-pres

jobs:
- name: ls-directory
  plan:
  - get: om
  - get: ci-repo
  - task: ls-directory
    file: ci-repo/tasks/ls-directory/task.yml
    input_mapping:
      directory: om
